language: ruby
rvm:
  - 2.2.2

script:
  - bundle install
  - bundle exec rake db:setup
  - bundle exec rake

env:
  global:
    - FORECAST_KEY=abc123
    - STRAVA_CLIENT_ID=1234
    - STRAVA_CLIENT_SECRET=def456
    - STRAVA_TOKEN=ghi789

services:
  - redis-server
